### ISSUE TITLE
Kinect

### ISSUE THREAD

**Issue by sschaeffner** [GoCodingGroup/MultiplicationTable#1]
- display player's footprints (height encoded as color)
- display player's old footprints

- Input event (Adapter) -> Same Interface for mouse and Kinect

**Comment by DominikHorn** [comment]
I managed to implement a foot stomping recognition but it does not work fully yet.
Problems that arose: 
* Kinect updates skeleton joint positions even when not moving by small amounts every frame. This makes gesture recognition harder.
* Recognized coordinates seem to change based on the angle the Kinect is positioned at. There apparently is a way to determin how the floor is oriented and therefore how Kinect is oriented. I'm not sure how to implement this feature though.
Both issues need further looking into.
