### ISSUE TITLE
Squashed changes from experimental in experimental_release

### ISSUE THREAD

**Issue by DominikHorn** [GoCodingGroup/MultiplicationTable#10]
I can't really come up with useful commits from experimental. Should I just squash it all into one commit (as has happened on experimental_release) or does this violate our "small commit"-policy to much?
@sschaeffner @hoelzel

**Comment by sschaeffner** [comment]
Should be fine if you kill your single experimental branch afterwards. Just use feature-[feature name] branches afterwards.

**Comment by sschaeffner** [comment]
I would actually recommend this git branching model: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by DominikHorn** [comment]
Okay I will kill experimental :(
![alt text](http://gph.is/14rHjYM)

**Comment by DominikHorn** [comment]
Okay, i will kill my lone experimental branch :(

![alt text](http://66.media.tumblr.com/9c1fbe400ccb840ae5907f75126c1874/tumblr_motcaaX8ut1sx2cido1_500.gif)

**Comment by DominikHorn** [comment]
>I would actually recommend this git branching model: http://nvie.com/posts/a-successful-git-branching-model/

wiki ;)

**Comment by sschaeffner** [comment]
currently editing...

**Comment by sschaeffner** [comment]
done editing. also provided a short set of instructions to not overdo it ;)

**Comment by DominikHorn** [comment]
Nice :) :+1: I pushed a new develop branch meanwhile

**Comment by hoelzel** [comment]
Hello,

the mentioned git branching model http://nvie.com/posts/a-successful-git-branching-model/
makes good sense to me, except the handling of the feature
branches. They suggest, that feature branches should  reside in
the developers repo only. I'd prefer them to exist in the origin
repo as well. We are only a group of three and there for the repo
isn't going to be a mess.  And this way discussing the code is
much easier as everybody can easily obtain the code.

Martin

**Comment by sschaeffner** [comment]
Makes sense to me, as long as we delete old feature branches on the origin.

**Comment by hoelzel** [comment]
Oh you've already anticipated my suggestion. I didn't read the wiki yet.
