### ISSUE TITLE
Calculate the ground level from Kinect-Sensor data.

### ISSUE THREAD

**Issue by hoelzel** [GoCodingGroup/MultiplicationTable#12]
Use kinects xyz stream to calculate the normal vector and the intercept with the z-axis of a ground representating plane.

**Comment by DominikHorn** [comment]
May we close this issue as implemented?

**Comment by hoelzel** [comment]
Closed as duplicate / partially rethought

**Comment by hoelzel** [comment]
Closed as duplicate / partially rethought.
