### ISSUE TITLE
Kinect v2 does not output its elevation angle

### ISSUE THREAD

**Issue by DominikHorn** [GoCodingGroup/MultiplicationTable#14]
Should we decide to use the Kinect v2, because it can recognize people more accurately and within a greater depth range, we must find a different way to determine the grounds position and orientation.

**Comment by hoelzel** [comment]
I'm trying to implement ground detection using the XYZ Data provided by the kinect device. Unfortunatly I'm not very succesfull.  I need help...

**Comment by DominikHorn** [comment]
May we close this as fixed?

**Comment by hoelzel** [comment]
Closed as duplicate / partially rethought
