### ISSUE TITLE
Game

### ISSUE THREAD

**Issue by sschaeffner** [GoCodingGroup/MultiplicationTable#2]
- display more bubbles
- display text in bubbles

**Comment by DominikHorn** [comment]
Multiple bubbles may be added as of commit #1451c85739572ffb578c3276b884046390c69e3c by calling the convenience method addBubble() inside of start() inside the GameController multiple times.

This, together with text rendering inside of bubbles is demonstrated in the experimental branch @ commit #66598e1cd009f96f7de17100e366e72283e1f4e8
