### ISSUE TITLE
Branch "master" is now a protected branch

### ISSUE THREAD

**Issue by DominikHorn** [GoCodingGroup/MultiplicationTable#5]
Every commit on master will stay there forever from now on. Once pushed there should be no necessity for changing any content of the commit, and if there really is, a separate new commit must be pushed.
I suggest the following scheme for collaborating with git (If we all agree on this we can put this in wiki):
* Keep commits locally for as long as is possible, compress them into logical commit blocks when pushing to master (F.e. if you have "Work in Progress" commits for a feature, merge them all into the commit that actually adds said feature). 
* Make a separate branch if experimental™ code has to be shared/looked at by others/needs to be uploaded for a meeting:
    1. git checkout -b <new_branch_name>
    2. git push -u origin <new_branch_name>
* If we decide to merge an experimental™ change with the master branch, the following procedure should avoid mess:
    1. git checkout <experimental™_branch_name>
    2. git rebase -i origin/master; // Clean up commits in this step aswell
    3. merge/push to master afterwards

Note: experimental™ is reserved as a branch name for this repo by @DominikHorn as long as this currently existing branch is not deleted/merged. This has nothing to do with being lazy when typing git branch names. All Rights Reserved.

**Comment by sschaeffner** [comment]
Seems legit. Makes sense to me. Approved.

@DominikHorn would you add this to the wiki?

**Comment by DominikHorn** [comment]
I'll add this tomorrow
