### ISSUE TITLE
Refactor code to be able to launch without kinect attached

### ISSUE THREAD

**Issue by sschaeffner** [GoCodingGroup/MultiplicationTable#6]
Refactor the code (especially the GameController.java class) to not directly interact with the kinect but rather use an interface for all input methods (mouse, kinect) and load one or more of the input methods at the beginning of the game.

**Comment by DominikHorn** [comment]
Hallo,
Kann den issue #6 nicht mehr finden. Wird aber natürlich alles noch refactored bevor ich auf den master pushe. 

Greetings from the dark side,
Dominik

**Comment by sschaeffner** [comment]
GitHub glitcht wohl ein bisschen rum…

Super :) Sobald das refactored ist, kannst du ja neue Issues erstellen, von denen ich mir dann auch mal eins schnappen kann, was unabhängig von der Kinect ist.

Ich würde auch vorschlagen, dass wir versuchen kleinere committs/issues zu haben, so dass man keine Angst haben muss, dass neuer Code komplett sinnlos ist, sobald jemand anderes von dem eigenen riesigen feature/experimental-branch merged.

Simon

**Comment by DominikHorn** [comment]
Hi,

hab jetzt nur erstmal kinect-mäßig soweit ausgelotet was wir mit Martin letzte Woche noch besprochen hatte, dafür musste auch das Spiel ein Stück weiter entwickelt werden. Gibt aber definitiv noch viele Sachen die gemacht werden müssen.:)

Gute Idee immer rein damit ins Wiki ;) 

Dominik

> Am 12.07.2016 um 18:09 schrieb Simon Schäffner <notifications@github.com>:
> 
> GitHub glitcht wohl ein bisschen rum…
> 
> Super :) Sobald das refactored ist, kannst du ja neue Issues erstellen, von denen ich mir dann auch mal eins schnappen kann, was unabhängig von der Kinect ist.
> 
> Ich würde auch vorschlagen, dass wir versuchen kleinere committs/issues zu haben, so dass man keine Angst haben muss, dass neuer Code komplett sinnlos ist, sobald jemand anderes von dem eigenen riesigen feature/experimental-branch merged.
> 
> Simon
>

**Comment by hoelzel** [comment]
Hallo,
      eine Schwierigkeit ist doch den Boden festzulegen. Vielleicht kann
      man was mit der Depthmap machen. Meine Idee ist im Zentrum zwei
      zueinander senkrechte Strecken durch Ausgleichsgeraden zu finden.
      Ich würde das mal untersuchen.
      Martin
      Am 12.07.2016 um 18:49 schrieb Dominik Horn:
    
    Hi,
      
      hab jetzt nur erstmal kinect-mäßig soweit ausgelotet was wir mit
      Martin letzte Woche noch besprochen hatte, dafür musste auch das
      Spiel ein Stück weiter entwickelt werden. Gibt aber definitiv noch
      viele Sachen die gemacht werden müssen.:)
      
      Gute Idee immer rein damit ins Wiki ;) 
      
      Dominik
      
      > Am 12.07.2016 um 18:09 schrieb Simon Schäffner
      <notifications@github.com>:
      > 
      > GitHub glitcht wohl ein bisschen rum…
      > 
      > Super :) Sobald das refactored ist, kannst du ja neue Issues
      erstellen, von denen ich mir dann auch mal eins schnappen kann,
      was unabhängig von der Kinect ist.
      > 
      > Ich würde auch vorschlagen, dass wir versuchen kleinere
      committs/issues zu haben, so dass man keine Angst haben muss, dass
      neuer Code komplett sinnlos ist, sobald jemand anderes von dem
      eigenen riesigen feature/experimental-branch merged.
      > 
      > Simon
      > 
      > > On 12 Jul 2016, at 18:04, Dominik Horn
      <notifications@github.com> wrote:
      > > 
      > > Hallo,
      > > Kann den issue #6 nicht mehr finden. Wird aber natürlich
      alles noch refactored bevor ich auf den master pushe. 
      > > 
      > > Greetings from the dark side,
      > > Dominik 
      > > 
      > > > Am 12.07.2016 um 18:00 schrieb Simon Schäffner
      <notifications@github.com>:
      > > > 
      > > > Assigned #6 to @DominikHorn.
      > > > 
      > > > —
      > > > You are receiving this because you were mentioned.
      > > > Reply to this email directly, view it on GitHub, or
      mute the thread.
      > > > 
      > > —
      > > You are receiving this because you authored the thread.
      > > Reply to this email directly, view it on GitHub
<https://github.com/GoCodingGroup/MultiplicationTable/issues/6#issuecomment-232095350>,
      or mute the thread
<https://github.com/notifications/unsubscribe/ADXxkUULmQMJ1xz7xxwbl6DKFzG4fxR5ks5qU7rxgaJpZM4JKjFd>.
      > > 
      > 
      > —
      > You are receiving this because you were mentioned.
      > Reply to this email directly, view it on GitHub, or mute the
      thread.
      > 
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by DominikHorn** [comment]
Die E-Mails werden direkt direkt auf Github geposted o.O

Zur Idee mit der Depthmap: Das klingt kompliziert, könnte jedoch ausgezeichnet funktionieren. 
Für den Fall, dass das dennoch zu aufwändig ist, könnten wir per Mathemagie aus kalibrierten Eckpunkten des Spielfelds eine Ebenengleichung für den Boden bestimmen und per Schnittpunktermittlung mit einer Gerade, welche parallel zur y Achse und durch den gemessenen Punkt verläuft, die Bodenkoordinaten an der Stelle (x,z) berechnen. Wahrscheinlich müssen wir aufgrund unterschiedlicher Kinect-Positionen in der Aula sowieso jedes mal bei einem Neustart des Spiels die Eckpunkte des Spielfeldes neu erkennen lassen, darum wäre das vielleicht auch als Fallback-Mechanismus geeignet. 

> Am 12.07.2016 um 20:40 schrieb hoelzel <notifications@github.com>:
> 
> 
> 
> 
> 
> 
> Hallo,
> eine Schwierigkeit ist doch den Boden festzulegen. Vielleicht kann
> man was mit der Depthmap machen. Meine Idee ist im Zentrum zwei
> zueinander senkrechte Strecken durch Ausgleichsgeraden zu finden.
> Ich würde das mal untersuchen.
> Martin
> Am 12.07.2016 um 18:49 schrieb Dominik Horn:
> 
> Hi,
> 
> hab jetzt nur erstmal kinect-mäßig soweit ausgelotet was wir mit
> Martin letzte Woche noch besprochen hatte, dafür musste auch das
> Spiel ein Stück weiter entwickelt werden. Gibt aber definitiv noch
> viele Sachen die gemacht werden müssen.:)
> 
> Gute Idee immer rein damit ins Wiki ;) 
> 
> Dominik
> 
> > Am 12.07.2016 um 18:09 schrieb Simon Schäffner
> <notifications@github.com>:
> > 
> > GitHub glitcht wohl ein bisschen rum…
> > 
> > Super :) Sobald das refactored ist, kannst du ja neue Issues
> erstellen, von denen ich mir dann auch mal eins schnappen kann,
> was unabhängig von der Kinect ist.
> > 
> > Ich würde auch vorschlagen, dass wir versuchen kleinere
> committs/issues zu haben, so dass man keine Angst haben muss, dass
> neuer Code komplett sinnlos ist, sobald jemand anderes von dem
> eigenen riesigen feature/experimental-branch merged.
> > 
> > Simon
> > 
> > > On 12 Jul 2016, at 18:04, Dominik Horn

**Comment by DominikHorn** [comment]
Achja und als follow-up: Da das direkt auf Github beim Issue #6 geposted wird, würde ich vorschlagen dass wir die Kommentare zur Depth-Map und zum Umgang mit git auf issue #4 bzw #5 schieben für die Übersichtlichkeit des Repos.

**Comment by DominikHorn** [comment]
Okay after having to force push since I messed up somewhere the main suggestions from this issue thread have been implemented. Refactoring is not finished though.
